// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.8
// source: internal/server/state/chat_map.proto

package state

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatMapConfidence int32

const (
	ChatMapConfidence_CHAT_MAP_CONFIDENCE_UNSPECIFIED ChatMapConfidence = 0
	ChatMapConfidence_VERIFIED                        ChatMapConfidence = 1
	ChatMapConfidence_SYNTHETIC                       ChatMapConfidence = 2
)

// Enum value maps for ChatMapConfidence.
var (
	ChatMapConfidence_name = map[int32]string{
		0: "CHAT_MAP_CONFIDENCE_UNSPECIFIED",
		1: "VERIFIED",
		2: "SYNTHETIC",
	}
	ChatMapConfidence_value = map[string]int32{
		"CHAT_MAP_CONFIDENCE_UNSPECIFIED": 0,
		"VERIFIED":                        1,
		"SYNTHETIC":                       2,
	}
)

func (x ChatMapConfidence) Enum() *ChatMapConfidence {
	p := new(ChatMapConfidence)
	*p = x
	return p
}

func (x ChatMapConfidence) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChatMapConfidence) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_server_state_chat_map_proto_enumTypes[0].Descriptor()
}

func (ChatMapConfidence) Type() protoreflect.EnumType {
	return &file_internal_server_state_chat_map_proto_enumTypes[0]
}

func (x ChatMapConfidence) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChatMapConfidence.Descriptor instead.
func (ChatMapConfidence) EnumDescriptor() ([]byte, []int) {
	return file_internal_server_state_chat_map_proto_rawDescGZIP(), []int{0}
}

type ChatMapDB struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Entries       []*ChatMapEntry        `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMapDB) Reset() {
	*x = ChatMapDB{}
	mi := &file_internal_server_state_chat_map_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMapDB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMapDB) ProtoMessage() {}

func (x *ChatMapDB) ProtoReflect() protoreflect.Message {
	mi := &file_internal_server_state_chat_map_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMapDB.ProtoReflect.Descriptor instead.
func (*ChatMapDB) Descriptor() ([]byte, []int) {
	return file_internal_server_state_chat_map_proto_rawDescGZIP(), []int{0}
}

func (x *ChatMapDB) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ChatMapDB) GetEntries() []*ChatMapEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type ChatMapEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RootHash      string                 `protobuf:"bytes,1,opt,name=root_hash,json=rootHash,proto3" json:"root_hash,omitempty"`
	ParentHash    string                 `protobuf:"bytes,2,opt,name=parent_hash,json=parentHash,proto3" json:"parent_hash,omitempty"`
	ChatId        string                 `protobuf:"bytes,3,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Rid           string                 `protobuf:"bytes,4,opt,name=rid,proto3" json:"rid,omitempty"`
	Rcid          string                 `protobuf:"bytes,5,opt,name=rcid,proto3" json:"rcid,omitempty"`
	Context       string                 `protobuf:"bytes,6,opt,name=context,proto3" json:"context,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	MessageCount  uint32                 `protobuf:"varint,8,opt,name=message_count,json=messageCount,proto3" json:"message_count,omitempty"`
	Confidence    ChatMapConfidence      `protobuf:"varint,9,opt,name=confidence,proto3,enum=gemini_web_cli.server.state.ChatMapConfidence" json:"confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMapEntry) Reset() {
	*x = ChatMapEntry{}
	mi := &file_internal_server_state_chat_map_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMapEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMapEntry) ProtoMessage() {}

func (x *ChatMapEntry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_server_state_chat_map_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMapEntry.ProtoReflect.Descriptor instead.
func (*ChatMapEntry) Descriptor() ([]byte, []int) {
	return file_internal_server_state_chat_map_proto_rawDescGZIP(), []int{1}
}

func (x *ChatMapEntry) GetRootHash() string {
	if x != nil {
		return x.RootHash
	}
	return ""
}

func (x *ChatMapEntry) GetParentHash() string {
	if x != nil {
		return x.ParentHash
	}
	return ""
}

func (x *ChatMapEntry) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *ChatMapEntry) GetRid() string {
	if x != nil {
		return x.Rid
	}
	return ""
}

func (x *ChatMapEntry) GetRcid() string {
	if x != nil {
		return x.Rcid
	}
	return ""
}

func (x *ChatMapEntry) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *ChatMapEntry) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *ChatMapEntry) GetMessageCount() uint32 {
	if x != nil {
		return x.MessageCount
	}
	return 0
}

func (x *ChatMapEntry) GetConfidence() ChatMapConfidence {
	if x != nil {
		return x.Confidence
	}
	return ChatMapConfidence_CHAT_MAP_CONFIDENCE_UNSPECIFIED
}

var File_internal_server_state_chat_map_proto protoreflect.FileDescriptor

const file_internal_server_state_chat_map_proto_rawDesc = "" +
	"\n" +
	"$internal/server/state/chat_map.proto\x12\x1bgemini_web_cli.server.state\"j\n" +
	"\tChatMapDB\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12C\n" +
	"\aentries\x18\x02 \x03(\v2).gemini_web_cli.server.state.ChatMapEntryR\aentries\"\xb9\x02\n" +
	"\fChatMapEntry\x12\x1b\n" +
	"\troot_hash\x18\x01 \x01(\tR\brootHash\x12\x1f\n" +
	"\vparent_hash\x18\x02 \x01(\tR\n" +
	"parentHash\x12\x17\n" +
	"\achat_id\x18\x03 \x01(\tR\x06chatId\x12\x10\n" +
	"\x03rid\x18\x04 \x01(\tR\x03rid\x12\x12\n" +
	"\x04rcid\x18\x05 \x01(\tR\x04rcid\x12\x18\n" +
	"\acontext\x18\x06 \x01(\tR\acontext\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\x03R\tupdatedAt\x12#\n" +
	"\rmessage_count\x18\b \x01(\rR\fmessageCount\x12N\n" +
	"\n" +
	"confidence\x18\t \x01(\x0e2..gemini_web_cli.server.state.ChatMapConfidenceR\n" +
	"confidence*U\n" +
	"\x11ChatMapConfidence\x12#\n" +
	"\x1fCHAT_MAP_CONFIDENCE_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bVERIFIED\x10\x01\x12\r\n" +
	"\tSYNTHETIC\x10\x02B@Z>github.com/Leechael/gemini-web-cli/internal/server/state;stateb\x06proto3"

var (
	file_internal_server_state_chat_map_proto_rawDescOnce sync.Once
	file_internal_server_state_chat_map_proto_rawDescData []byte
)

func file_internal_server_state_chat_map_proto_rawDescGZIP() []byte {
	file_internal_server_state_chat_map_proto_rawDescOnce.Do(func() {
		file_internal_server_state_chat_map_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_server_state_chat_map_proto_rawDesc), len(file_internal_server_state_chat_map_proto_rawDesc)))
	})
	return file_internal_server_state_chat_map_proto_rawDescData
}

var file_internal_server_state_chat_map_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_server_state_chat_map_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_server_state_chat_map_proto_goTypes = []any{
	(ChatMapConfidence)(0), // 0: gemini_web_cli.server.state.ChatMapConfidence
	(*ChatMapDB)(nil),      // 1: gemini_web_cli.server.state.ChatMapDB
	(*ChatMapEntry)(nil),   // 2: gemini_web_cli.server.state.ChatMapEntry
}
var file_internal_server_state_chat_map_proto_depIdxs = []int32{
	2, // 0: gemini_web_cli.server.state.ChatMapDB.entries:type_name -> gemini_web_cli.server.state.ChatMapEntry
	0, // 1: gemini_web_cli.server.state.ChatMapEntry.confidence:type_name -> gemini_web_cli.server.state.ChatMapConfidence
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_server_state_chat_map_proto_init() }
func file_internal_server_state_chat_map_proto_init() {
	if File_internal_server_state_chat_map_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_server_state_chat_map_proto_rawDesc), len(file_internal_server_state_chat_map_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_server_state_chat_map_proto_goTypes,
		DependencyIndexes: file_internal_server_state_chat_map_proto_depIdxs,
		EnumInfos:         file_internal_server_state_chat_map_proto_enumTypes,
		MessageInfos:      file_internal_server_state_chat_map_proto_msgTypes,
	}.Build()
	File_internal_server_state_chat_map_proto = out.File
	file_internal_server_state_chat_map_proto_goTypes = nil
	file_internal_server_state_chat_map_proto_depIdxs = nil
}
